### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by pmadhikar**
Added some instructions to get started. 

Please someone test on Windows. Mac should be okay, but that should be tested too.

### CODE REVIEW

**Comment by zeffii** [comment]
I can only test windows.

For the windows git instructions, this is the same for `windows vista` and upwards. After reading 
http://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link i realized that I
 use a directory junction  `/j` which I thought was a _symbolic link_, but isn't -- the end result for local directories is pretty much the same. Maybe it would serve to include a statement like:

> both /d and /j are good options, of the two /j requires no elevated user privileges so if /d fails, then use /j

**Comment by pmadhikar** [comment]
Okay, I made those changes.

**Comment by pmadhikar** [comment]
Oh, btw, could you please try these steps on Windows command prompt and git bash? I don't even know if anyone even uses the windows command prompt over git bash.

**Comment by zeffii** [comment]
I can confirm if git is installed correctly, that's how to do it on windows too.
image
The red asterix section is because that folder already had a folder called BioBlender.

**Pull request merged**
