### PR TITLE
Getting started instructions

### PR DESCRIPTION
**Pull request by pmadhikar**
This will make getting started easy for new people. I put the instructions in readme.md so that is visible on the first page of the repo. This is common practice for other software as well. I don't have windows so I haven't tried the windows instructions, but I think they are correct. The instructions are correct for Linux and should work on Macs too, but someone should test it. 

We should also add some instructions with the github app. 

This can go towards fixing issue #13

### CODE REVIEW

**Comment by zeffii** [comment]
I'm in favour of this pull request but maybe augmented with a prerequisite checklist. 
- pymol
- maybe python 2.7 for certain scripts

**Comment by pmadhikar** [comment]
Good idea, I'll add that stuff in.

Doesn't Blender use its own python distribution? Python3.4? Is 2.7 still
needed with that?

**Comment by zeffii** [comment]
the dependency on Python 2.6 / 2.7 is only because some included 3rd party scripts are written in <=2.7 python  syntax

**Comment by pmadhikar** [comment]
I messed up the branching, will close this PR and open a new one.

**Pull request closed without merging**
