### PR TITLE
Master main first fixes

### PR DESCRIPTION
**Pull request by zeffii**
adding these as the first commits, they are essential to start things rolling

### CODE REVIEW

**Comment by MonZop** [comment]
Sorry, I am not sure.
Should I do something?
(pls. if you think I'm really ingorant, and a little stupid, just consider that I studied biology, and that's what I know and do every day!)

**Comment by zeffii** [comment]
not at all.
thatsall

**Comment by MonZop** [comment]
OK, thanks.
And now?, which branch is that I should use for testing?

**Comment by zeffii** [comment]
At the moment both `master` and `master_main_first_fixes` have the core of my changes / introductions. I'm very eager to start implementing things like `code style`, but first the expected functionality must be restored. 

I'm still not at the point where I can say I know what all features do or should be doing, without a manual I rely on the code and comparing the code with the older versions.

**Comment by MonZop** [comment]
OK, in this case I will use the master_main_first_fixes (but how do you change the font?) with blender 273, and point to problems there (in the proper issue #).

**Comment by zeffii** [comment]
master should now support all version 2.68 - 2.7x , the import code attempts to offer a generic solution.

Change which font? in these threads? using the symbol that looks like single quote mark, but is called a 'back tick'  
```
one of these ` not one of these '
```

**Comment by zeffii** [comment]
more info about how to format the text: https://guides.github.com/features/mastering-markdown/

**Pull request merged**
