### PR TITLE
Alternative mlp with emptytest

### PR DESCRIPTION
**Pull request by zeffii**
pull request only, do not accept yet

### CODE REVIEW

**Comment by zeffii** [comment]
don't Merge yet.

@MonZop it would be great if you could test this branch vs the current BioBlender-master. If there are features broken from this branch compared to the Master, please describe them in detail so I can focus on those.

I would like to push this branch to master soon, but not until it is at least on par with the features of Master ( so if something is broken in Master.. and also broken in this branch..thats OK). My point here is find any regressions ( something being worse than before ) . You know this App better than I.

**Comment by MonZop** [comment]
I cannot get this version in Blender
mlp_alternative
(i admit I am still using the inefficient way of downloading the zip file, change name, remove all BioBlender old stuff etc.)

**Comment by zeffii** [comment]
I am tempted to make a script to automate some of this process, it is needlessly convoluted for the end user who doesn't use Git.
how

If this is what you're doing, that's OK, you probably need to 
- untick the addon from preferences
- ctrl+U,  (to save this in your default .blend)
- close blender
- open blender
- retick addon
- ctrl+U to store again. 
- test

**Comment by MonZop** [comment]
What you suggest is what I do. I repeated several times.
I also unzipped the packet, renamed BioBlender and re-zipped.
For what i can understand (i may be wrong) the error seems to be inside : it cannot find some modules

**Comment by zeffii** [comment]
@MonZop I have no immediate solution to that, I run the same code here. very frustrating. 0_o

**Comment by zeffii** [comment]
@MonZop when you open blender, open into the Python Console (Not the Text Editor) and enter 
```python
bpy.utils.script_paths()
```
will look like: 
image

any of the locations listed might contain a BioBlender folder, make sure you only have one BioBlender folder, if there are more then this can lead to a source of confusion for Python.

**Comment by zeffii** [comment]
The branch should now be gone, it can be revived using Restore Branch, if the code ever needs to be looked at. It almost worked..

**Comment by zeffii** [comment]
Good catch @MonZop , I restored the branch.

I'll be less active for a while. it's perhaps too hectic here at home :)

**Pull request closed without merging**
